# Generated by Django 3.1.7 on 2021-08-02 09:21

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('event_description', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=50)),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('end_date', models.DateField(default=datetime.datetime.now)),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('end_time', models.TimeField(default=django.utils.timezone.now)),
                ('isCanceled', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
                ('isFinished', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='EventRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('date_sent', models.DateField(default=datetime.datetime.now)),
                ('time_sent', models.TimeField(default=django.utils.timezone.now)),
                ('request_type', models.CharField(max_length=50)),
                ('isPending', models.BooleanField(default=True)),
                ('isConfirmed', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'event_request',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=255)),
                ('rating', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.ManyToManyField(related_name='organizer', to='organizer.Event')),
                ('request', models.ManyToManyField(to='organizer.EventRequest')),
            ],
            options={
                'db_table': 'organizer',
            },
        ),
    ]
