# Generated by Django 3.1.7 on 2021-08-02 09:14

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EventRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('date_sent', models.DateField(default=datetime.datetime.now)),
                ('time_sent', models.TimeField(default=django.utils.timezone.now)),
                ('request_type', models.CharField(max_length=50)),
                ('isPending', models.BooleanField(default=True)),
                ('isConfirmed', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'event_request',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=255)),
                ('rating', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='account_ptr',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='gender',
        ),
        migrations.AddField(
            model_name='organizer',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='organizer',
            table='organizer',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.AddField(
            model_name='organizer',
            name='events',
            field=models.ManyToManyField(related_name='organizer', to='organizer.Event'),
        ),
        migrations.AddField(
            model_name='organizer',
            name='request',
            field=models.ManyToManyField(to='organizer.EventRequest'),
        ),
    ]
